### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [hvanandel/prj-rev-bwfs-dasmoto#5]
Nice job on this project! I really liked your usage of a general h2 class, and how clean and easy to read your code was. In terms of improvement, I recommend removing the font-weight:bold on your h2s, using spans instead of divs in your HTML, and setting the font-family once using a universal/body selector.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the superb work! ^_^

**Comment by hvanandel** [comment]
Thank you for the review and considerations. I will go back in and edit. Cheers!
